# Generated by Django 5.2.3 on 2025-06-14 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("social", "0001_initial"),
        ("stickers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="sticker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="stickers.sticker",
                verbose_name="Стикер",
            ),
        ),
    ]
